# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Positive Tinker
tagline:          'If at first you don't succeed, redefine success.'
description:      ''
url:              https://positivetinker.com

author:
  name:           'Michael'
  url:            https://positivetinker.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MikeTV/PositiveTinker
